#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define G 9.81
#define MOVING_THRESHOLD 0.0001
#define PLAYER_RADIUS 20
#define PLAYER_MASS 12
#define NUM_TEAM_PLAYERS 5
#define BALL_RADIUS 14
#define BALL_MASS 4
#define MAX_AXIS_VELOCITY 500
#define MIN_AXIS_VELOCITY -1 * MAX_AXIS_VELOCITY
#define TIME_DELTA 0.01
#define FPS 120
#define NET_SIZE 6 * PLAYER_RADIUS
#define PLAYGROUND_WIDTH 960
#define PLAYGROUND_HEIGHT 640
#define DECELERATION 4 * G

#endif
